services:
  namesrv:
    image: apache/rocketmq:5.3.0
    container_name: rmqnamesrv
    platform: linux/amd64
    ports:
      - 9876:9876
    environment:
      - NAMESRV_ADDR=127.0.0.1:9876
    command: sh mqnamesrv

  broker:
    image: apache/rocketmq:5.3.0
    container_name: rmqbroker
    platform: linux/amd64
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      - NAMESRV_ADDR=127.0.0.1:9876
      - BROKER_ID=0
      - BROKER_NAME=DefaultBroker
      - BROKER_IP1=127.0.0.1
    command: sh mqbroker -n namesrv:9876

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqdashboard
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false