-- Clean up historical data
DELETE FROM sys_model WHERE model_name = 'SysModel';
DELETE FROM sys_field WHERE model_name = 'SysModel';

-- Insert model metadata
INSERT INTO sys_model(label_name, model_name, table_name, description, default_order, display_name, timeline, soft_delete, multi_tenant, version_lock, partition_field)
    VALUES('System Model', 'SysModel', 'sys_model', '', 'modelName', 'modelName,labelName', false, false,  false, false, '');

INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('ID', 'id', 'id', 'SysModel', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('App ID', 'appId', 'app_id', 'SysModel', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Label Name', 'labelName', 'label_name', 'SysModel', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Model Name', 'modelName', 'model_name', 'SysModel', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Enable Soft Delete', 'softDelete', 'soft_delete', 'SysModel', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Default Order2', 'defaultOrder', 'default_order', 'SysModel', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 256, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Display Name', 'displayName', 'display_name', 'SysModel', '', 'MultiString', '', '', '', '', 0, 0, '', '', '', "''", 255, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Search Name', 'searchName', 'search_name', 'SysModel', '', 'MultiString', '', '', '', '', 0, 0, '', '', '', "''", 255, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Table Name', 'tableName', 'table_name', 'SysModel', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Is Timeline Model', 'timeline', 'timeline', 'SysModel', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('ID Strategy', 'idStrategy', 'id_strategy', 'SysModel', '', 'Option', 'IdStrategy', '', '', '', 0, 0, '', '', '', "'DbAutoId'", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Storage Type', 'storageType', 'storage_type', 'SysModel', '', 'Option', 'StorageType', '', '', '', 0, 0, '', '', '', "'RDBMS'", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Enable Version Lock', 'versionLock', 'version_lock', 'SysModel', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Enable Multi-tenancy', 'multiTenant', 'multi_tenant', 'SysModel', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Partition Field', 'partitionField', 'partition_field', 'SysModel', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Description', 'description', 'description', 'SysModel', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 256, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Model Fields', 'modelFields', 'model_fields', 'SysModel', '', 'OneToMany', '', 'SysField', 'modelId', '', true, true, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created Time', 'createdTime', 'created_time', 'SysModel', '', 'DateTime', '', '', '', '', 0, 0, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created By', 'createdBy', 'created_by', 'SysModel', '', 'String', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created ID', 'createdId', 'created_id', 'SysModel', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated Time', 'updatedTime', 'updated_time', 'SysModel', '', 'DateTime', '', '', '', '', 0, 0, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated ID', 'updatedId', 'updated_id', 'SysModel', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated By', 'updatedBy', 'updated_by', 'SysModel', '', 'String', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Disabled', 'disabled', 'disabled', 'SysModel', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');

-- Clean up historical data
DELETE FROM sys_model WHERE model_name = 'SysField';
DELETE FROM sys_field WHERE model_name = 'SysField';

-- Insert model metadata
INSERT INTO sys_model(label_name, model_name, table_name, description, default_order, display_name, timeline, soft_delete, multi_tenant, version_lock, partition_field)
    VALUES('System Field', 'SysField', 'sys_field', '', '', 'labelName', false, false,  false, false, '');

-- Insert field metadata
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('ID', 'id', 'id', 'SysField', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('App ID', 'appId', 'app_id', 'SysField', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Label Name', 'labelName', 'label_name', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Field Name', 'fieldName', 'field_name', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Column Name', 'columnName', 'column_name', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, true, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Model Name', 'modelName', 'model_name', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Model ID', 'modelId', 'model_id', 'SysField', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Description', 'description', 'description', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 256, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Field Type', 'fieldType', 'field_type', 'SysField', '', 'Option', 'FieldType', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Option Set Code', 'optionSetCode', 'option_set_code', 'SysField', 'Set when FieldType is Option or MultiOption', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Related Model', 'relatedModel', 'related_model', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Related Field', 'relatedField', 'related_field', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Inverse Link Field', 'inverseLinkField', 'inverse_link_field', 'SysField', 'Set when FieldType is ManyToMany', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Auto Bind Many', 'autoBindMany', 'auto_bind_many', 'SysField', 'Whether to read the XToMany field automatically', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Auto Expand Many', 'autoExpandMany', 'auto_expand_many', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Cascaded Field', 'cascadedField', 'cascaded_field', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 256, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Display Name', 'displayName', 'display_name', 'SysField', '', 'MultiString', '', '', '', '', 0, 0, '', '', '', "''", 255, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Filters', 'filters', 'filters', 'SysField', 'Filters for relational fields.', 'String', '', '', '', '', 0, 0, '', '', '', "''", 256, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Default Value', 'defaultValue', 'default_value', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 256, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Length', 'length', 'length', 'SysField', '', 'Integer', '', '', '', '', 0, 0, '', '', '', "0", 11, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Scale', 'scale', 'scale', 'SysField', '', 'Integer', '', '', '', '', 0, 0, '', '', '', "0", 4, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Is Required', 'required', 'required', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Is Readonly', 'readonly', 'readonly', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Hidden', 'hidden', 'hidden', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Translatable', 'translatable', 'translatable', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Copyable', 'copyable', 'copyable', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Unsearchable', 'unsearchable', 'unsearchable', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Is Computed', 'computed', 'computed', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Expression', 'expression', 'expression', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "", 20000, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Dynamic Field', 'dynamic', 'dynamic', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Is Encrypted', 'encrypted', 'encrypted', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Masking Type', 'maskingType', 'masking_type', 'SysField', '', 'Option', 'MaskingType', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created Time', 'createdTime', 'created_time', 'SysField', '', 'DateTime', '', '', '', '', 0, 0, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created ID', 'createdId', 'created_id', 'SysField', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created By', 'createdBy', 'created_by', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated Time', 'updatedTime', 'updated_time', 'SysField', '', 'DateTime', '', '', '', '', 0, 0, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated ID', 'updatedId', 'updated_id', 'SysField', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated By', 'updatedBy', 'updated_by', 'SysField', '', 'String', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Disabled', 'disabled', 'disabled', 'SysField', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');

-- Clean up historical data
DELETE FROM sys_model WHERE model_name = 'SysOptionSet';
DELETE FROM sys_field WHERE model_name = 'SysOptionSet';

-- Insert model metadata
INSERT INTO sys_model(label_name, model_name, table_name, description, default_order, display_name, timeline, soft_delete, multi_tenant, version_lock, partition_field)
    VALUES('Option Set', 'SysOptionSet', 'sys_option_set', '', '', 'name', false, false,  false, false, '');

-- Insert field metadata
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('ID', 'id', 'id', 'SysOptionSet', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('App ID', 'appId', 'app_id', 'SysOptionSet', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Option Set Name', 'name', 'name', 'SysOptionSet', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Option Set Code', 'optionSetCode', 'option_set_code', 'SysOptionSet', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Option Items', 'optionItems', 'option_items', 'SysOptionSet', '', 'OneToMany', '', 'SysOptionItem', 'optionSetId', '', true, 0, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Description', 'description', 'description', 'SysOptionSet', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 256, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created Time', 'createdTime', 'created_time', 'SysOptionSet', '', 'DateTime', '', '', '', '', 0, 0, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created ID', 'createdId', 'created_id', 'SysOptionSet', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created By', 'createdBy', 'created_by', 'SysOptionSet', '', 'String', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated Time', 'updatedTime', 'updated_time', 'SysOptionSet', '', 'DateTime', '', '', '', '', 0, 0, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated ID', 'updatedId', 'updated_id', 'SysOptionSet', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated By', 'updatedBy', 'updated_by', 'SysOptionSet', '', 'String', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Disabled', 'disabled', 'disabled', 'SysOptionSet', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');

-- Clean up historical data
DELETE FROM sys_model WHERE model_name = 'SysOptionItem';
DELETE FROM sys_field WHERE model_name = 'SysOptionItem';

-- Insert model metadata
INSERT INTO sys_model(label_name, model_name, table_name, description, default_order, display_name, timeline, soft_delete, multi_tenant, version_lock, partition_field)
    VALUES('Option Set Items', 'SysOptionItem', 'sys_option_item', '', 'optionSetCode,sequence', 'itemCode,itemName', false, false,  false, false, '');

-- Insert field metadata
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('ID', 'id', 'id', 'SysOptionItem', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('App ID', 'appId', 'app_id', 'SysOptionItem', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Option Set ID', 'optionSetId', 'option_set_id', 'SysOptionItem', '', 'ManyToOne', '', 'SysOptionSet', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Option Set Code', 'optionSetCode', 'option_set_code', 'SysOptionItem', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Sequence', 'sequence', 'sequence', 'SysOptionItem', '', 'Integer', '', '', '', '', 0, 0, '', '', '', "1", 11, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Item Code', 'itemCode', 'item_code', 'SysOptionItem', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Item Name', 'itemName', 'item_name', 'SysOptionItem', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, true, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Parent Item Code', 'parentItemCode', 'parent_item_code', 'SysOptionItem', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Item Color', 'itemColor', 'item_color', 'SysOptionItem', '', 'Option', 'OptionItemColor', '', '', '', 0, 0, '', '', '', "''", 64, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Description', 'description', 'description', 'SysOptionItem', '', 'String', '', '', '', '', 0, 0, '', '', '', "''", 256, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created Time', 'createdTime', 'created_time', 'SysOptionItem', '', 'DateTime', '', '', '', '', 0, 0, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created ID', 'createdId', 'created_id', 'SysOptionItem', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Created By', 'createdBy', 'created_by', 'SysOptionItem', '', 'String', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated Time', 'updatedTime', 'updated_time', 'SysOptionItem', '', 'DateTime', '', '', '', '', 0, 0, '', '', '', "", 0, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated ID', 'updatedId', 'updated_id', 'SysOptionItem', '', 'Long', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Updated By', 'updatedBy', 'updated_by', 'SysOptionItem', '', 'String', '', '', '', '', 0, 0, '', '', '', "", 32, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');
INSERT INTO sys_field(label_name, field_name, column_name, model_name, description, field_type, option_set_code, related_model, related_field, inverse_link_field, auto_bind_many, auto_expand_many, cascaded_field, display_name, filters, default_value, length, scale, required, readonly, translatable, copyable, unsearchable, computed, expression, dynamic, encrypted, masking_type)
    VALUES('Disabled', 'disabled', 'disabled', 'SysOptionItem', '', 'Boolean', '', '', '', '', 0, 0, '', '', '', "0", 1, 0, false, 0, 0, 0, 0, 0, '', 0, 0, '');

