services:

  elasticsearch:
    image: elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ~/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:8.15.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

#  fluent-bit:
#    image: fluent/fluent-bit:3.1.6
#    volumes:
#      - /var/log:/var/log
#      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
#    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
#    depends_on:
#      - elasticsearch
#    ports:
#      - "24224:24224"
