debug: false
system:
  name: Demo Application
security:
  encryption:
    password: 12345678
    algorithm: AESEncryption

spring:
  data:
    redis:
      root-key: demo_test
      host: localhost
      port: 6379
      database: 0
      password: admin
      timeout: 1000
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HikariPool-Demo
#  elasticsearch:
#    cluster: http://localhost:9200
#    username: your_username
#    password: your_password
#    index:
#      changelog: demo_test_changelog
