debug: false
system:
  name: Demo Application
  default-language: en-US
  enable-auth: false
  multi-tenancy:
    enable: true
security:
  encryption:
    password: 12345678
    algorithm: AESEncryption

spring:
  data:
    redis:
      root-key: demo_dev
      host: localhost
      port: 6379
      database: 0
      password: admin
      timeout: 1000
  datasource:
#    dynamic:
#      enable: true
#      # mode: read-write-separation, switch-by-model, multi-tenancy-isolated, multi-datasource(default)
#      mode: multi-datasource
#      datasource:
#        primary:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/demo
#          username: admin
#          password: admin
#        db1:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/db1
#          username: root
#          password: admin
#        db2:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/db2
#          username: admin
#          password: admin
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HikariPool-Demo
  elasticsearch:
    cluster: http://localhost:9200
    username: your_username
    password: your_password
    index:
      changelog: demo_dev_changelog

rocketmq:
  name-server: localhost:9876
  producer:
    group: my-producer-group
    send-message-timeout: 3000
  consumer:
    group: my-consumer-group
  topics:
    async-import:
      topic: dev_demo_async_import
      group: dev_demo_async_import_group
    cron-task:
      topic: dev_demo_cron_task
      flow-group: dev_demo_cron_task_flow_group
    change-log:
      topic: dev_demo_change_log
      flow-group: dev_demo_change_log_flow_group
      persist-group: dev_demo_change_log_persist_group
    flow-async-task:
      topic: dev_demo_flow_async_task
      group: dev_demo_flow_async_task_group
    flow-event:
      topic: dev_demo_flow_event
      group: dev_demo_flow_event_group
    inner-broadcast:
      topic: dev_demo_inner_broadcast
      group: dev_demo_inner_broadcast_group

oss:
  type: minio
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: demo-app
  sub-dir: