spring:
  application:
    name: demo-app
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cache:
    redis:
      # Global default expiration period for redis cache
      time-to-live: 30d
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jmx:
    # Turn off JVM remote calls
    enabled: false
  freemarker:
    # Turn off automatic inspection of freemarker templates
    checkTemplateLocation: false
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 80
  shutdown: graceful
  servlet:
    encoding:
      # set http CharacterEncoding to UTF-8
      force: true
    context-path: /api/demo
  tomcat:
    threads:
      max: 600
      min-spare: 30
    accept-count: 600
    relaxed-query-chars: "[,]"
    basedir: ./temp
    max-swallow-size: 20MB

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info
  health:
    elasticsearch:
      enabled: false
    mail:
      enabled: false

logging:
  level:
    root: info

springdoc:
  writer-with-order-by-keys: true
  api-docs:
    # Turn off in production environment
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operations-sorter: alpha
