services:

  redis:
    image: redis:7.2.5-alpine
    command: redis-server --requirepass admin
    ports:
      - 6379:6379

#  postgres:
#    image: postgres:16.3-alpine
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=demo
#    volumes:
#      - ~/data/postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      # For testing environment only
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=demo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ~/data/mysql/demo:/var/lib/mysql
      # Specify the directory containing the initial SQL scripts
      - ./init_mysql:/docker-entrypoint-initdb.d

  demo-app:
    image: openmeta/demo-app:0.7.3
    ports:
      - 80:80
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
      - SPRING_DATA_REDIS_HOST=redis
      - ROCKETMQ_NAME_SERVER=localhost:9876
      - SPRING_ELASTICSEARCH_CLUSTER=http://localhost:9200
      - SPRING_ELASTICSEARCH_USERNAME=your_username
      - SPRING_ELASTICSEARCH_PASSWORD=your_password
      - SPRING_ELASTICSEARCH_INDEX_CHANGELOG=demo_dev_changelog
      - OSS_TYPE=minio
      - OSS_ENDPOINT=http://localhost:9000
      - OSS_ACCESS_KEY=minioadmin
      - OSS_SECRET_KEY=minioadmin
      - OSS_BUCKET=demo-app
    depends_on:
      - redis
      - mysql

#  nginx:
#    image: nginx:1.27.0-alpine
#    ports:
#      - 80:80
##    depends_on:
##      - openmeta
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
