services:

  redis:
    image: redis:7.2.5-alpine
    command: redis-server --requirepass admin
    ports:
      - 6379:6379

#  postgres:
#    image: postgres:16.3-alpine
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      # For testing environment only
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=demo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ~/mysql_data:/var/lib/mysql
      # Specify the directory containing the initial SQL scripts
      - ./init_mysql:/docker-entrypoint-initdb.d

  openmeta:
    image: openmeta/demo-app:0.3.2
    ports:
      - 80:80
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis
      - mysql

#  nginx:
#    image: nginx:1.27.0-alpine
#    ports:
#      - 80:80
##    depends_on:
##      - openmeta
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
